var annotated_dup =
[
    [ "illumism", null, [
      [ "Attack", "classillumism_1_1_attack.html", "classillumism_1_1_attack" ],
      [ "BackGround", "classillumism_1_1_back_ground.html", "classillumism_1_1_back_ground" ],
      [ "BonusPoint", "classillumism_1_1_bonus_point.html", "classillumism_1_1_bonus_point" ],
      [ "BOSS", "classillumism_1_1_b_o_s_s.html", "classillumism_1_1_b_o_s_s" ],
      [ "BOSS_CENTER", "classillumism_1_1_b_o_s_s___c_e_n_t_e_r.html", "classillumism_1_1_b_o_s_s___c_e_n_t_e_r" ],
      [ "BOSS_LEFT", "classillumism_1_1_b_o_s_s___l_e_f_t.html", "classillumism_1_1_b_o_s_s___l_e_f_t" ],
      [ "BOSS_RIGHT", "classillumism_1_1_b_o_s_s___r_i_g_h_t.html", "classillumism_1_1_b_o_s_s___r_i_g_h_t" ],
      [ "Bullet", "classillumism_1_1_bullet.html", "classillumism_1_1_bullet" ],
      [ "Camera", "classillumism_1_1_camera.html", "classillumism_1_1_camera" ],
      [ "Combo", "classillumism_1_1_combo.html", "classillumism_1_1_combo" ],
      [ "CoopMoveController", "classillumism_1_1_coop_move_controller.html", "classillumism_1_1_coop_move_controller" ],
      [ "CoopMoveObject", "classillumism_1_1_coop_move_object.html", "classillumism_1_1_coop_move_object" ],
      [ "CrossLaser", "classillumism_1_1_cross_laser.html", "classillumism_1_1_cross_laser" ],
      [ "FallAttack", "classillumism_1_1_fall_attack.html", "classillumism_1_1_fall_attack" ],
      [ "Flybar_UI", "classillumism_1_1_flybar___u_i.html", "classillumism_1_1_flybar___u_i" ],
      [ "Game", "classillumism_1_1_game.html", "classillumism_1_1_game" ],
      [ "GameSign", "classillumism_1_1_game_sign.html", "classillumism_1_1_game_sign" ],
      [ "GameUIController", "classillumism_1_1_game_u_i_controller.html", "classillumism_1_1_game_u_i_controller" ],
      [ "GroundAttack", "classillumism_1_1_ground_attack.html", "classillumism_1_1_ground_attack" ],
      [ "GroundParticle", "classillumism_1_1_ground_particle.html", "classillumism_1_1_ground_particle" ],
      [ "HitEffect", "classillumism_1_1_hit_effect.html", "classillumism_1_1_hit_effect" ],
      [ "HPbar_UI", "classillumism_1_1_h_pbar___u_i.html", "classillumism_1_1_h_pbar___u_i" ],
      [ "LandingParticle", "classillumism_1_1_landing_particle.html", "classillumism_1_1_landing_particle" ],
      [ "LaserAttack", "classillumism_1_1_laser_attack.html", "classillumism_1_1_laser_attack" ],
      [ "ModeBase", "classillumism_1_1_mode_base.html", "classillumism_1_1_mode_base" ],
      [ "ModeCredit", "classillumism_1_1_mode_credit.html", "classillumism_1_1_mode_credit" ],
      [ "ModeGame", "classillumism_1_1_mode_game.html", "classillumism_1_1_mode_game" ],
      [ "ModeLogo", "classillumism_1_1_mode_logo.html", "classillumism_1_1_mode_logo" ],
      [ "ModeMainMenu", "classillumism_1_1_mode_main_menu.html", "classillumism_1_1_mode_main_menu" ],
      [ "ModeOperation", "classillumism_1_1_mode_operation.html", "classillumism_1_1_mode_operation" ],
      [ "ModeOverlay", "classillumism_1_1_mode_overlay.html", "classillumism_1_1_mode_overlay" ],
      [ "ModeResult", "classillumism_1_1_mode_result.html", "classillumism_1_1_mode_result" ],
      [ "ModeScoreBonus", "classillumism_1_1_mode_score_bonus.html", "classillumism_1_1_mode_score_bonus" ],
      [ "ModeSelectChara", "classillumism_1_1_mode_select_chara.html", "classillumism_1_1_mode_select_chara" ],
      [ "ModeServer", "classillumism_1_1_mode_server.html", "classillumism_1_1_mode_server" ],
      [ "ModeTitle", "classillumism_1_1_mode_title.html", "classillumism_1_1_mode_title" ],
      [ "ModeTutorial", "classillumism_1_1_mode_tutorial.html", "classillumism_1_1_mode_tutorial" ],
      [ "ObjectBase", "classillumism_1_1_object_base.html", "classillumism_1_1_object_base" ],
      [ "ObjectServer", "classillumism_1_1_object_server.html", "classillumism_1_1_object_server" ],
      [ "Particle", "classillumism_1_1_particle.html", "classillumism_1_1_particle" ],
      [ "Player", "classillumism_1_1_player.html", "classillumism_1_1_player" ],
      [ "PlayerUIController", "classillumism_1_1_player_u_i_controller.html", "classillumism_1_1_player_u_i_controller" ],
      [ "PointNumber_UI", "classillumism_1_1_point_number___u_i.html", "classillumism_1_1_point_number___u_i" ],
      [ "PointObject", "classillumism_1_1_point_object.html", "classillumism_1_1_point_object" ],
      [ "ResourceServer", "classillumism_1_1_resource_server.html", null ],
      [ "ResultPoint", "classillumism_1_1_result_point.html", "classillumism_1_1_result_point" ],
      [ "SPMove", "classillumism_1_1_s_p_move.html", "classillumism_1_1_s_p_move" ],
      [ "SPmove_UI", "classillumism_1_1_s_pmove___u_i.html", "classillumism_1_1_s_pmove___u_i" ],
      [ "Spotlight", "classillumism_1_1_spotlight.html", "classillumism_1_1_spotlight" ],
      [ "SpotlightController", "classillumism_1_1_spotlight_controller.html", "classillumism_1_1_spotlight_controller" ],
      [ "SpotLightHit", "classillumism_1_1_spot_light_hit.html", "classillumism_1_1_spot_light_hit" ],
      [ "Time_UI", "classillumism_1_1_time___u_i.html", "classillumism_1_1_time___u_i" ],
      [ "TouchObject", "classillumism_1_1_touch_object.html", "classillumism_1_1_touch_object" ],
      [ "TouchObjectController", "classillumism_1_1_touch_object_controller.html", "classillumism_1_1_touch_object_controller" ],
      [ "TouchParticle", "classillumism_1_1_touch_particle.html", "classillumism_1_1_touch_particle" ],
      [ "TouchSuccessEffect", "classillumism_1_1_touch_success_effect.html", "classillumism_1_1_touch_success_effect" ]
    ] ],
    [ "sound", null, [
      [ "PlayWAVE", "classsound_1_1_play_w_a_v_e.html", "classsound_1_1_play_w_a_v_e" ],
      [ "WAVEReader", "classsound_1_1_w_a_v_e_reader.html", "classsound_1_1_w_a_v_e_reader" ]
    ] ],
    [ "utility", null, [
      [ "Easing", "classutility_1_1_easing.html", null ],
      [ "EffectComponent", "classutility_1_1_effect_component.html", "classutility_1_1_effect_component" ]
    ] ],
    [ "MyFadeXAPO", "class_my_fade_x_a_p_o.html", null ],
    [ "MyHighPassFilterXAPO", "class_my_high_pass_filter_x_a_p_o.html", null ],
    [ "MyLowPassFilterXAPO", "class_my_low_pass_filter_x_a_p_o.html", null ],
    [ "MyPeakMeterXAPO", "class_my_peak_meter_x_a_p_o.html", null ],
    [ "MyStereoDownMixXAPO", "class_my_stereo_down_mix_x_a_p_o.html", null ]
];